In [2]:
"""
Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.
"""

# Employee class
class Employee:
    # Data member to count the number of employees
    count = 0 
    
    def __init__(self, first_name, family_name, salary, department):
        self._first_name = first_name    # Initialize name
        self._family_name = family_name  # Initialize family 
        self._salary = salary            # Initialize salary
        self._department = department    # Initialize department
        # Count increases when a new employee is added
        Employee.count += 1

    def __str__(self):
        return f"{self.__class__.__name__}: {self._first_name} {self._family_name}\n" \
               f"Salary: {self._salary}", f"Department: {self._department}"

# Function to calculate average salary
def average_salary(e_list):
    total_salary = sum(e._salary for e in e_list)
    return total_salary / len(e_list) if len(e_list) > 0 else 0

# FulltimeEmployee class & it inherits the properties of Employee class
class FullTimeEmployee(Employee):
    def __init__(self, name, family, salary, department, type="Full-Time"):
        # Calling the constructor of the parent class
        super().__init__(name, family, salary, department)
        # Additional attribute for FullTimeEmployee
        self.type = type


if __name__ == '__main__':
    try:
        # Created instances of different employee types
        e1 = Employee('Donald', 'Trump', 676879, 'HR')
        e2 = FullTimeEmployee('Elon', 'Musk', 546576,'Developement', )
        e3 = Employee('Taylor', 'Swift', 98909, 'Analyst')
        e4 = Employee('Joe', 'Biden', 75356,'IT' )
        e5 = FullTimeEmployee('Rayan', 'Gosling', 94372, 'Manager','Full-time')
        e6 = FullTimeEmployee('Narendra', 'Modi', 75463, 'Advertisement')

        # Create a list of employee objects
        e_list = [e1, e2, e3, e4, e5, e6]

        print("Number of Employees count: ", Employee.count)
        print("Average Salary of Employees: ", average_salary(e_list))

    except ValueError as e:
        print(e)  # Print error message if a ValueError occurs during object creation


Number of Employees count:  6
Average Salary of Employees:  261259.16666666666


In [1]:
"""
2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)
"""

import numpy as np

def replace_max_with_zero(arr):
    # Reshape the array to a 4 by 5 matrix
    reshaped_array = arr.reshape(4, 5)
    # Finds max values in each row
    max = np.argmax(reshaped_array, axis=1)
    # Replace max values with 0 in each row
    reshaped_array[np.arange(reshaped_array.shape[0]), max] = 0
    return reshaped_array

if __name__ == "__main__":
    # Random vector of size 20 with floats in the range 1-20
    random_vector = np.random.uniform(1, 20, 20)

    print("Original Array: ")
    print(random_vector)

    # Calls the function to reshape and replace max values with 0
    result_array = replace_max_with_zero(random_vector)

    print("\nReshaped Array with Max Values Replaced by 0 (axis 1): ")
    print(result_array)


Original Array: 
[ 2.04391979 13.57551316 11.89654703  7.02705226 18.54430972 11.02668367
 18.67915395  1.66549874  2.76916739  2.69034035  7.09736227 12.49228219
  8.79051143  9.83916107  3.13951979 16.35411603 11.69919163 13.1045387
 18.14720158  4.61830278]

Reshaped Array with Max Values Replaced by 0 (axis 1): 
[[ 2.04391979 13.57551316 11.89654703  7.02705226  0.        ]
 [11.02668367  0.          1.66549874  2.76916739  2.69034035]
 [ 7.09736227  0.          8.79051143  9.83916107  3.13951979]
 [16.35411603 11.69919163 13.1045387   0.          4.61830278]]
